version: "2"
services:
  app:
    image: kthanasio/tua-mesa-back
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw