"""Renomeando a coluna PASSWORD_HASH para PASSWORD na tabela USER

Revision ID: 0c666ca7a902
Revises: 1002be51b95b
Create Date: 2020-09-18 01:24:18.226305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c666ca7a902'
down_revision = '1002be51b95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
