"""Adicionando tabela COMPANY_CONFIG

Revision ID: 1002be51b95b
Revises: 51e43205175f
Create Date: 2020-09-18 00:53:18.430561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1002be51b95b'
down_revision = '51e43205175f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_config_company_id'), 'company_config', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_config_config_id'), 'company_config', ['config_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_config_config_id'), table_name='company_config')
    op.drop_index(op.f('ix_company_config_company_id'), table_name='company_config')
    op.drop_table('company_config')
    # ### end Alembic commands ###
