"""Deixando campos da tabela LINE_UP como Nullable

Revision ID: 1d646f725de1
Revises: 81769e689e0c
Create Date: 2020-09-20 19:46:36.038098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d646f725de1'
down_revision = '81769e689e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('line_up', 'cancelled_call_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('line_up', 'completed_call_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('line_up', 'first_call_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('line_up', 'second_call_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('line_up', 'second_call_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('line_up', 'first_call_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('line_up', 'completed_call_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('line_up', 'cancelled_call_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
