"""Adicionando coluna name como Unique na tabela WaintingLine

Revision ID: 273d2b7e1ae2
Revises: c0f25537d56e
Create Date: 2020-09-19 23:35:12.186201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273d2b7e1ae2'
down_revision = 'c0f25537d56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waiting_line_name', table_name='waiting_line')
    op.create_index(op.f('ix_waiting_line_name'), 'waiting_line', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiting_line_name'), table_name='waiting_line')
    op.create_index('ix_waiting_line_name', 'waiting_line', ['name'], unique=False)
    # ### end Alembic commands ###
