"""Adicionando tabela LINE_UP

Revision ID: 50b6ad0170b2
Revises: ba66a5866122
Create Date: 2020-09-18 00:26:55.607791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b6ad0170b2'
down_revision = 'ba66a5866122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waiting_line_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('first_call_at', sa.DateTime(), nullable=False),
    sa.Column('second_call_at', sa.DateTime(), nullable=False),
    sa.Column('completed_call_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_call_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['waiting_line_id'], ['waiting_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_up_customer_id'), 'line_up', ['customer_id'], unique=False)
    op.create_index(op.f('ix_line_up_waiting_line_id'), 'line_up', ['waiting_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_up_waiting_line_id'), table_name='line_up')
    op.drop_index(op.f('ix_line_up_customer_id'), table_name='line_up')
    op.drop_table('line_up')
    # ### end Alembic commands ###
