"""Adicionando tabela WAITING_LINE

Revision ID: ba66a5866122
Revises: 9447d5b0d480
Create Date: 2020-09-15 00:20:44.727337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba66a5866122'
down_revision = '9447d5b0d480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiting_line_company_id'), 'waiting_line', ['company_id'], unique=False)
    op.create_index(op.f('ix_waiting_line_name'), 'waiting_line', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiting_line_name'), table_name='waiting_line')
    op.drop_index(op.f('ix_waiting_line_company_id'), table_name='waiting_line')
    op.drop_table('waiting_line')
    # ### end Alembic commands ###
