"""Adicionando coluna name + company como Unique na tabela WaintingLine

Revision ID: c4fdd8561569
Revises: 273d2b7e1ae2
Create Date: 2020-09-19 23:49:30.420780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fdd8561569'
down_revision = '273d2b7e1ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_company_wait_line_uc', 'waiting_line', ['company_id', 'name'])
    op.drop_index('ix_waiting_line_name', table_name='waiting_line')
    op.create_index(op.f('ix_waiting_line_name'), 'waiting_line', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiting_line_name'), table_name='waiting_line')
    op.create_index('ix_waiting_line_name', 'waiting_line', ['name'], unique=True)
    op.drop_constraint('_company_wait_line_uc', 'waiting_line', type_='unique')
    # ### end Alembic commands ###
