"""Adicionando coluna admin_email na tabela company

Revision ID: fec0ea69f3b0
Revises: 1d646f725de1
Create Date: 2020-09-25 14:08:24.748082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec0ea69f3b0'
down_revision = '1d646f725de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('admin_email', sa.String(length=100), nullable=True))
    op.create_unique_constraint('_admin_email_uc', 'company', ['admin_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_admin_email_uc', 'company', type_='unique')
    op.drop_column('company', 'admin_email')
    # ### end Alembic commands ###
